using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace KTC_SalesAppWAPI.Helpers
{
    public class EnDecriptHelper
    {
        string mykey = "0oAst}{";        
        readonly byte[] salt = Encoding.ASCII.GetBytes("{F@st/Track*SB0i(Sdn.)Bhd.^S@lt&For%Encrypti0n}");

        public string EncriptMD5String(string originalString)
        {
            //this is the full code to generate md5 
            Byte[] generatedBytes, originalBytes;
            MD5 md5 = new MD5CryptoServiceProvider();

            //convert string data to array of bytes
            originalBytes = ASCIIEncoding.Default.GetBytes(originalString);

            //compute hash on generated byte array
            generatedBytes = md5.ComputeHash(originalBytes);

            //display hash bytes as readable string as the hash code generated will contain dash(-)
            // to remove that Replace function of Regex is used here....
            return Regex.Replace(BitConverter.ToString(generatedBytes), "-", "");
        }

        public string EncryptString(string stringtoencrypt)
        {
            var algorithm = GetAlgorithm();
            byte[] encryptedBytes;
            using (ICryptoTransform encryptor = algorithm.CreateEncryptor(algorithm.Key, algorithm.IV))
            {
                byte[] bytesToEncrypt = Encoding.UTF8.GetBytes(stringtoencrypt);
                encryptedBytes = InMemoryCrypt(bytesToEncrypt, encryptor);
            }
            return Convert.ToBase64String(encryptedBytes);
        }

        RijndaelManaged GetAlgorithm()
        {
            var key = new Rfc2898DeriveBytes(mykey, salt);
            var algorithm = new RijndaelManaged();
            int bytesForKey = algorithm.KeySize / 8;
            int bytesForIV = algorithm.BlockSize / 8;
            algorithm.Key = key.GetBytes(bytesForKey);
            algorithm.IV = key.GetBytes(bytesForIV);
            return algorithm;
        }
        byte[] InMemoryCrypt(byte[] data, ICryptoTransform transform)
        {
            MemoryStream memory = new MemoryStream();
            using (Stream stream = new CryptoStream(memory, transform, CryptoStreamMode.Write))
            {
                stream.Write(data, 0, data.Length);
            }
            return memory.ToArray();
        }
    }
}
