using System;
namespace KTC_SalesAppWAPI.Models.CompanyInfo
{
     public class ADM1
     {
         #region fields for table ADM1
         public string CurrPeriod { get; set; }
         public string Street { get; set; }
         public string StreetF { get; set; }
         public string Block { get; set; }
         public string BlockF { get; set; }
         public string City { get; set; }
         public string CityF { get; set; }
         public string ZipCode { get; set; }
         public string ZipCodeF { get; set; }
         public string County { get; set; }
         public string CountyF { get; set; }
         public string State { get; set; }
         public string Country { get; set; }
         public string IntrntAdrs { get; set; }
         public int Code { get; set; }
         public string AssType { get; set; }
         public string CompnyType { get; set; }
         public string NatureBiz { get; set; }
         public string TaxIdNum4 { get; set; }
         public string TaxIdNum5 { get; set; }
         public string TaxIdNum6 { get; set; }
         public int LogInstanc { get; set; }
         public string AddrType { get; set; }
         public string AddrTypeF { get; set; }
         public string StreetNo { get; set; }
         public string StreetNoF { get; set; }
         public string Building { get; set; }
         public string BuildingF { get; set; }
         public string EccNo { get; set; }
         public string CERegNo { get; set; }
         public string CERange { get; set; }
         public string CEDivision { get; set; }
         public string CeComRate { get; set; }
         public string MenuCode { get; set; }
         public string Jurisd { get; set; }
         public int SnapShotId { get; set; }
         public int STDCode { get; set; }
         public int STDCodeF { get; set; }
         public int CompNature { get; set; }
         public int EconActT { get; set; }
         public string CredCOrig { get; set; }
         public string IPIPeriod { get; set; }
         public int CoopAssocT { get; set; }
         public string DspIBPDoc { get; set; }
         public string DspIITMDoc { get; set; }
         public int ProfTax { get; set; }
         public int CompQualif { get; set; }
         public int DeclType { get; set; }
         public string IPITaxCon { get; set; }
         public string ISVATRegNo { get; set; }
         public string ISVATRegEx { get; set; }
         public string ISObligLvl { get; set; }
         public string ISTaxState { get; set; }
         public string ISComDecID { get; set; }
         public string OKDPNum { get; set; }
         public string ISValidKey { get; set; }
         public string ISDnsce { get; set; }
         public string ISDfltPath { get; set; }
         public string ISSimpProc { get; set; }
         public string ISForceCmp { get; set; }
         public string ISCstRecSt { get; set; }
         public int ISDfltInct { get; set; }
         public int ISDfCPEx { get; set; }
         public int ISDfCPIm { get; set; }
         public int ISDfNTEx { get; set; }
         public int ISDfNTIm { get; set; }
         public int ISDfPortEx { get; set; }
         public int ISDfPortIm { get; set; }
         public int ISDfSPEx { get; set; }
         public int ISDfSPIm { get; set; }
         public int ISDfCSTEx { get; set; }
         public int ISDfCSTIm { get; set; }
         public int ISDfTMEx { get; set; }
         public int ISDfTMIm { get; set; }
         public short ISDeclDept { get; set; }
         public string ISExlDocQt { get; set; }
         public decimal ISDocQtLm { get; set; }
         public string ISExlDocAm { get; set; }
         public decimal ISDocAmLm { get; set; }
         public string ISDspNMass { get; set; }
         public string ImInfSup { get; set; }
         public string Free2 { get; set; }
         public string CommerReg { get; set; }
         public DateTime DateOfInc { get; set; }
         public string SPEDProf { get; set; }
         public int EnvTypeNFe { get; set; }
         public string Opt4ICMS { get; set; }
         public string ISInstIntr { get; set; }
         public string GlblLocNum { get; set; }
         public string PTLedgeGen { get; set; }
         public string BZStRegID { get; set; }
         public string BZStSendID { get; set; }
         public string PostInVat { get; set; }
         public string EnbEATrns { get; set; }
         public string EnbEAInv { get; set; }
         public string AuthUser { get; set; }
         public string AuthPwd { get; set; }
         public string UrlGoods { get; set; }
         public string UrlInvType { get; set; }
         public int ElGoodsFmt { get; set; }
         public int ElInvFmt { get; set; }
         public string ElDigiCert { get; set; }
         public DateTime TaxRptFrm { get; set; }
         public string Suframa { get; set; }
         public string EnbInItIQI { get; set; }
         public string EnbInItINC { get; set; }
         public string ExtRevAct { get; set; }
         public string IsStartup { get; set; }
         public string IsCUITMndt { get; set; }
         public string LnMlBrnch { get; set; }
         public string DfBrnchPh { get; set; }
         public string AplShipPch { get; set; }
         public string AsnBrnchBP { get; set; }
         public string ApyPRinAT { get; set; }
         public string ApyDRinAT { get; set; }
         public string EnMlBrkInv { get; set; }
         public string PEFilePath { get; set; }
         public string EnableGDPR { get; set; }
         #endregion fields for table ADM1
     }
}

