using System;
namespace KTC_SalesAppWAPI.Models.CompanyInfo
{
     public class OADM
     {
         #region fields for table OADM
         public string CompnyName { get; set; }
         public string CompnyAddr { get; set; }
         public string Country { get; set; }
         public string PrintHeadr { get; set; }
         public string Phone1 { get; set; }
         public string Phone2 { get; set; }
         public string Fax { get; set; }
         public string E_Mail { get; set; }
         public string Manager { get; set; }
         public string CompType { get; set; }
         public string MainCurncy { get; set; }
         public string SysCurrncy { get; set; }
         public string DispPosDeb { get; set; }
         public short DefLengthU { get; set; }
         public short DefWeightU { get; set; }
         public string DfltVendPM { get; set; }
         public string DirectRate { get; set; }
         public decimal MinAmnt347 { get; set; }
         public string AutoITW { get; set; }
         public string BankCountr { get; set; }
         public string TaxIdNum { get; set; }
         public string RevOffice { get; set; }
         public string FreeZoneNo { get; set; }
         public string DdctFileNo { get; set; }
         public string VatCharge { get; set; }
         public string PayOutVat { get; set; }
         public decimal VatPrcnt { get; set; }
         public decimal DpsitPrcnt { get; set; }
         public decimal IncomeTax { get; set; }
         public string VendorDdct { get; set; }
         public string CustmrDdct { get; set; }
         public decimal DdctPercnt { get; set; }
         public DateTime DdctExpire { get; set; }
         public string DdctOffice { get; set; }
         public int EURepSqntl { get; set; }
         public int BoxRptSeq { get; set; }
         public string WTLiable { get; set; }
         public string DfltCustPM { get; set; }
         public string AllowFuPos { get; set; }
         public string UseProdWip { get; set; }
         public string CurrPeriod { get; set; }
         public string XmlPath { get; set; }
         public int DflBnkKey { get; set; }
         public string BSInstled { get; set; }
         public string UseShpdGd { get; set; }
         public string UseExtRpt { get; set; }
         public string ERpPerType { get; set; }
         public string DfSVatExmp { get; set; }
         public string DfPVatExmp { get; set; }
         public string Manager1 { get; set; }
         public string Manager1F { get; set; }
         public string CCMask { get; set; }
         public string ObligLimit { get; set; }
         public string CreditLimt { get; set; }
         public string SalesLimit { get; set; }
         public string DlnLimit { get; set; }
         public string OrderLimit { get; set; }
         public string AddDlnBlnc { get; set; }
         public string CreditDpst { get; set; }
         public string MultiLang { get; set; }
         public int DbVers { get; set; }
         public int ApplVers { get; set; }
         public string DflWebSite { get; set; }
         public string DflFTPSite { get; set; }
         public string UseTax { get; set; }
         public string RevisionPo { get; set; }
         public string Reindex { get; set; }
         public string DllPath { get; set; }
         public string TaxIdValid { get; set; }
         public string PchName { get; set; }
         public string RpcName { get; set; }
         public string PdnName { get; set; }
         public string RpdName { get; set; }
         public string PorName { get; set; }
         public string LevelWarn { get; set; }
         public string CrdCommUse { get; set; }
         public string ItmCommUse { get; set; }
         public string SlpCommUse { get; set; }
         public short DfCustTerm { get; set; }
         public short DfVendTerm { get; set; }
         public string SaleProfit { get; set; }
         public short CostPrcLst { get; set; }
         public string GrossBySal { get; set; }
         public string TreePricOn { get; set; }
         public string AddVat { get; set; }
         public string BaseFld { get; set; }
         public string ClosedQuot { get; set; }
         public string UseCode { get; set; }
         public string Code1 { get; set; }
         public string Code2 { get; set; }
         public string Code3 { get; set; }
         public string Code4 { get; set; }
         public short Color { get; set; }
         public short SumDec { get; set; }
         public short QtyDec { get; set; }
         public short PriceDec { get; set; }
         public short RateDec { get; set; }
         public short PercentDec { get; set; }
         public short MeasureDec { get; set; }
         public string DdAutoRun { get; set; }
         public DateTime DdNextDue { get; set; }
         public short DdHour { get; set; }
         public string CmpnyAddrF { get; set; }
         public string DflTaxCode { get; set; }
         public string PrintHdrF { get; set; }
         public string Phone1F { get; set; }
         public string Phone2F { get; set; }
         public string FaxF { get; set; }
         public string ManagerF { get; set; }
         public string TimeFormat { get; set; }
         public string CigCup { get; set; }
         public string DateFormat { get; set; }
         public string DateSep { get; set; }
         public string FcNoBlnc { get; set; }
         public string ChangeRdr { get; set; }
         public string MultiCurr { get; set; }
         public string PickParDlv { get; set; }
         public decimal MaxTaxIncr { get; set; }
         public short ISRType { get; set; }
         public decimal MaxTaxDecr { get; set; }
         public string RoundRmrk { get; set; }
         public string ISRBillerI { get; set; }
         public int UpdStamp { get; set; }
         public string SysCNoEdit { get; set; }
         public string RefDNoEdit { get; set; }
         public string DfltWhs { get; set; }
         public string TaxDNoEdit { get; set; }
         public string DfSVatItem { get; set; }
         public string DfSVatServ { get; set; }
         public string DfPVatItem { get; set; }
         public string DfPVatServ { get; set; }
         public string DoBudget { get; set; }
         public string CustIdNum { get; set; }
         public string BgtBlock { get; set; }
         public string BgtWarning { get; set; }
         public string BdgtPORDoc { get; set; }
         public string BdgtAcctng { get; set; }
         public int BdgtDflt { get; set; }
         public string ContInvnt { get; set; }
         public string InvntSystm { get; set; }
         public string ApplicIFRS { get; set; }
         public short StartYear { get; set; }
         public short According { get; set; }
         public string MltpBrnchs { get; set; }
         public string EnblSrvTax { get; set; }
         public int DftRCN { get; set; }
         public string RoundVat { get; set; }
         public string BdgtPDNDoc { get; set; }
         public string IRSFileNo { get; set; }
         public string DeferrTax { get; set; }
         public decimal DflIntrst { get; set; }
         public short DfltSlp { get; set; }
         public short DflCrCard { get; set; }
         public string DflBnkCode { get; set; }
         public string DflBnkAcct { get; set; }
         public string DflBranch { get; set; }
         public string UsePaSys { get; set; }
         public string Serv_Usr { get; set; }
         public string Serv_Pass { get; set; }
         public string ParamPath { get; set; }
         public string ExcelPath { get; set; }
         public string TaxIdNum2 { get; set; }
         public string TaxIdNum3 { get; set; }
         public string DecSep { get; set; }
         public string ThousSep { get; set; }
         public string CurOnRight { get; set; }
         public string WarnByWhs { get; set; }
         public int DflBnkAcKy { get; set; }
         public string PriceSys { get; set; }
         public int DftPVL { get; set; }
         public string useDdctTrc { get; set; }
         public string useDocWrf { get; set; }
         public string BtchStatus { get; set; }
         public string OrderBatch { get; set; }
         public string GLMethod { get; set; }
         public string SetSriUniq { get; set; }
         public string SriUniqFld { get; set; }
         public int MaxHistory { get; set; }
         public string TaxRateDet { get; set; }
         public string RefreshQty { get; set; }
         public string StockNoBas { get; set; }
         public int MaxCntRows { get; set; }
         public string CentPmtInc { get; set; }
         public string CentPmtOut { get; set; }
         public string ChCtrAPAct { get; set; }
         public string ChCtrARAct { get; set; }
         public string PACUsrName { get; set; }
         public string PACPasswrd { get; set; }
         public string CaredType { get; set; }
         public string PBSNumber { get; set; }
         public string PBSGroupNo { get; set; }
         public string OrgNumber { get; set; }
         public string ActSep { get; set; }
         public string DspBokpWin { get; set; }
         public string SHandleWT { get; set; }
         public string SDfltWT { get; set; }
         public string IncresGlAc { get; set; }
         public string PHandleWT { get; set; }
         public string PDfltWT { get; set; }
         public string ExWTLiabl { get; set; }
         public int EDocSeqNum { get; set; }
         public string AllowPostZ { get; set; }
         public decimal PostDiffR { get; set; }
         public string EnableRO { get; set; }
         public DateTime UalLastDel { get; set; }
         public int UalKeepDay { get; set; }
         public string NegAmount { get; set; }
         public string EnbDocOpt { get; set; }
         public string HldCode { get; set; }
         public string AlphaDoc { get; set; }
         public string EDocURL2 { get; set; }
         public string EnPriceMod { get; set; }
         public string TaaSEnable { get; set; }
         public string TaaSUser { get; set; }
         public string OrderBlock { get; set; }
         public string RoundMthd { get; set; }
         public string AdrsFromWH { get; set; }
         public string OrderParty { get; set; }
         public string CrtfcateNO { get; set; }
         public DateTime ExpireDate { get; set; }
         public string NINum { get; set; }
         public string TaaSPass { get; set; }
         public string TaaSAutURL { get; set; }
         public string CfwAsnMust { get; set; }
         public int CfwInDflt { get; set; }
         public int CfwOutDflt { get; set; }
         public string TaaSURL { get; set; }
         public string TaaSSaleAc { get; set; }
         public string TaxRegime { get; set; }
         public string AliasName { get; set; }
         public string DftJPELine { get; set; }
         public string RdrConfrmd { get; set; }
         public string PorConfrmd { get; set; }
         public string TaaSPurcAc { get; set; }
         public string AdvImagePr { get; set; }
         public int ChfAcc { get; set; }
         public string TaxMethod { get; set; }
         public int CEO { get; set; }
         public short WllPprDsp { get; set; }
         public string WallPaper { get; set; }
         public string RndToTDec { get; set; }
         public string SDfltITWT { get; set; }
         public string PDfltITWT { get; set; }
         public string CheckFiles { get; set; }
         public string DsplyRates { get; set; }
         public string DfActCurr { get; set; }
         public string defTaxVend { get; set; }
         public string RcrFlag { get; set; }
         public string RclFlag { get; set; }
         public string ContactLog { get; set; }
         public string ShowNewMsg { get; set; }
         public string OpenCdt { get; set; }
         public string AutoVat { get; set; }
         public string ConsumeFCT { get; set; }
         public string ConsumeMtd { get; set; }
         public int DaysBack { get; set; }
         public int DaysFwrd { get; set; }
         public string IsPAPrn { get; set; }
         public string ShowNewTsk { get; set; }
         public string TaxCodeCst { get; set; }
         public string TaxCodeVnd { get; set; }
         public string State { get; set; }
         public int CharMonth { get; set; }
         public string free83 { get; set; }
         public short ScreenLock { get; set; }
         public string OpenCredit { get; set; }
         public string OpenDps { get; set; }
         public string AltBOEPost { get; set; }
         public string LDiscTotal { get; set; }
         public int Code { get; set; }
         public string DfltDunTrm { get; set; }
         public string Profession { get; set; }
         public short AlertPolFr { get; set; }
         public short DfltCDP { get; set; }
         public int LogInstanc { get; set; }
         public DateTime UpdateDate { get; set; }
         public short UserSign { get; set; }
         public string DflBCACode { get; set; }
         public string IgrAllCash { get; set; }
         public string TaxPayerRf { get; set; }
         public string EmployerRf { get; set; }
         public string PStatAutCh { get; set; }
         public short PStatDelay { get; set; }
         public string RepBusType { get; set; }
         public string RepBusOthr { get; set; }
         public string BrachNum { get; set; }
         public string BuisnesDsc { get; set; }
         public string ReptMethod { get; set; }
         public string AcctMethod { get; set; }
         public string Bookpitype { get; set; }
         public string ActSoftNam { get; set; }
         public string OpnClsRmrk { get; set; }
         public string TaxRndRule { get; set; }
         public string NegTax { get; set; }
         public string ZeroLine { get; set; }
         public string GBOpenFile { get; set; }
         public string GBIntface { get; set; }
         public short DfltCDPV { get; set; }
         public decimal OnHldPert { get; set; }
         public string WTRndRule { get; set; }
         public decimal GPPrcntSrv { get; set; }
         public string DspFrznBP { get; set; }
         public string DspFrznITM { get; set; }
         public decimal WTAccumAmt { get; set; }
         public string NewDPRCus { get; set; }
         public string ServNature { get; set; }
         public string PickLimit { get; set; }
         public decimal WTAccAmtAR { get; set; }
         public string UseProdPL { get; set; }
         public short QueryDec { get; set; }
         public string ExRtDefTax { get; set; }
         public string BoletoPath { get; set; }
         public short UserSign2 { get; set; }
         public DateTime MMLastImpD { get; set; }
         public string CpyExhRate { get; set; }
         public int MapService { get; set; }
         public int ODWFreq { get; set; }
         public string GTSOutPath { get; set; }
         public string UseMltDims { get; set; }
         public string MDStyle { get; set; }
         public string GTSInPath { get; set; }
         public string GTSSep { get; set; }
         public int GTSDftChk { get; set; }
         public int GTSDftPye { get; set; }
         public decimal GTSMaxAmt { get; set; }
         public string RspOverAmt { get; set; }
         public string DRBlock1 { get; set; }
         public string DRBlock2 { get; set; }
         public string DRBlock3 { get; set; }
         public string DRBlock4 { get; set; }
         public string DRBlock5 { get; set; }
         public string PrjBlock { get; set; }
         public string SimReport { get; set; }
         public int SnapShotId { get; set; }
         public string BackOrder { get; set; }
         public string HQLocation { get; set; }
         public string DigCrtPath { get; set; }
         public short DflWTS { get; set; }
         public string EnbApprDI { get; set; }
         public string ChBPSerie { get; set; }
         public string ChItmSerie { get; set; }
         public int ETRTaxOffi { get; set; }
         public string ETRTaxPers { get; set; }
         public int EDocExpFrm { get; set; }
         public string PCN874RTyp { get; set; }
         public string BTWDecProv { get; set; }
         public string BTWDcPrvID { get; set; }
         public string BTWName { get; set; }
         public string BTWStreet { get; set; }
         public string BTWCity { get; set; }
         public string BTWZip { get; set; }
         public string BTWPhone { get; set; }
         public int BTWOB { get; set; }
         public int BTWICP { get; set; }
         public int BTWOBFmt { get; set; }
         public int BTWICPFmt { get; set; }
         public string ETRPhoneNo { get; set; }
         public string EDTestMode { get; set; }
         public string EDocGenTyp { get; set; }
         public int EDocRptFmt { get; set; }
         public string EDocPass { get; set; }
         public string EDProcess { get; set; }
         public string PAC { get; set; }
         public string NotifAlert { get; set; }
         public string NotifEmail { get; set; }
         public int EDocUDQCat { get; set; }
         public string EOutputPth { get; set; }
         public int EDelDocFrm { get; set; }
         public int EDocPmnFmt { get; set; }
         public string EDocURL1 { get; set; }
         public string ETRFaxNo { get; set; }
         public string ETRMgrPhn { get; set; }
         public int EDFormat { get; set; }
         public int AIDFormat { get; set; }
         public string CrtLineRFQ { get; set; }
         public string DflJET { get; set; }
         public string OnlyPaidIn { get; set; }
         public string PDDEnabled { get; set; }
         public int MaxDays4DD { get; set; }
         public string AutoAddUoM { get; set; }
         public string AutoAddPkg { get; set; }
         public string BinActivat { get; set; }
         public short IssuePriBy { get; set; }
         public string InstFixAst { get; set; }
         public string DeprecCalc { get; set; }
         public string FixAstMod { get; set; }
         public string SopPath { get; set; }
         public string NewAcctDe { get; set; }
         public string ClnZeroPln { get; set; }
         public string CmdDisBoth { get; set; }
         public int CnclMaxDay { get; set; }
         public string AttachPath { get; set; }
         public string ConfigPath { get; set; }
         public string WrkshtPath { get; set; }
         public decimal ICDifExPe1 { get; set; }
         public decimal ICDifExPe2 { get; set; }
         public string ClsZoDiffR { get; set; }
         public string ClsNoConfi { get; set; }
         public string DTWPath { get; set; }
         public string DfltByEml { get; set; }
         public short CreditDay1 { get; set; }
         public string INVOBPrice { get; set; }
         public string SplitFBSh { get; set; }
         public string NotifyRqr { get; set; }
         public string DeactivFA { get; set; }
         public string CshDctFA { get; set; }
         public string SendAlert { get; set; }
         public string BdgtPRQDOC { get; set; }
         public string IsReuseNum { get; set; }
         public string IsReuseNFN { get; set; }
         public string SIPLReport { get; set; }
         public string SIPLDoc { get; set; }
         public string SIPLSeting { get; set; }
         public string PriceProcM { get; set; }
         public string ChkQtyINV { get; set; }
         public string EnbAdvATP { get; set; }
         public string EnblCase { get; set; }
         public string EnbSupplC { get; set; }
         public string MBAOnPer { get; set; }
         public string MBAOnAP { get; set; }
         public string MBAOnAR { get; set; }
         public string ApyBsActSP { get; set; }
         public string ApyBsActPV { get; set; }
         public string ApyBsActPL { get; set; }
         public string IsUpdNstdB { get; set; }
         public string SnBDfltSB { get; set; }
         public string OneBOneRec { get; set; }
         public string ReptCurrcy { get; set; }
         public decimal ICDifExPe3 { get; set; }
         public string INCSingToV { get; set; }
         public string POrCByINC { get; set; }
         public string EnbNegPym { get; set; }
         public string SirenNo { get; set; }
         public string SEPACredID { get; set; }
         public string InstitCode { get; set; }
         public int ECDFormat { get; set; }
         public string ApyDRinPEC { get; set; }
         public string ApyPRinPEC { get; set; }
         public string TaxPyerSta { get; set; }
         public int MaxINVRptR { get; set; }
         public string DftResWhs { get; set; }
         public string AutoResWhs { get; set; }
         public string InActRpt { get; set; }
         public string InActMkt { get; set; }
         public string InActPln { get; set; }
         public string StartFrom { get; set; }
         public short Months { get; set; }
         public short Days { get; set; }
         public string JEInFATran { get; set; }
         public short TPLId { get; set; }
         public string TxtSrch { get; set; }
         public string ApyIBtoACT { get; set; }
         public string JeUnGroup { get; set; }
         public string IgnoreAdde { get; set; }
         public string EnterAsTab { get; set; }
         public string MouseOnly { get; set; }
         public string PrjMngmnt { get; set; }
         public string ElectrDocs { get; set; }
         public string DotAsSep { get; set; }
         public string DoMngMth { get; set; }
         public string AlwBPNOwn { get; set; }
         public string EmptyPKL { get; set; }
         public string ExcNInvItm { get; set; }
         public short PayRefCalc { get; set; }
         public string MultiSched { get; set; }
         public string CloseWipV { get; set; }
         public decimal onHldLimt { get; set; }
         public string EnbApUpDoc { get; set; }
         public string EnbApUpDft { get; set; }
         public string EnPacking { get; set; }
         public string BlockZeroQ { get; set; }
         public string NegStoLv { get; set; }
         public string EnUpdBAPln { get; set; }
         public string BAOpPOR { get; set; }
         public string BAOpPDN { get; set; }
         public string BAOpAcctng { get; set; }
         public string AssgnOBAAP { get; set; }
         public string AssngOBAAR { get; set; }
         public string ApyToNewBP { get; set; }
         public string PrrConfrmd { get; set; }
         public string RrrConfrmd { get; set; }
         public int DflSeries { get; set; }
         public string EnblLC { get; set; }
         public string DflAcct { get; set; }
         public string SmtpServer { get; set; }
         public string SmtpPort { get; set; }
         public string SmtpName { get; set; }
         public string SmtpPasswd { get; set; }
         public string SmtpEncode { get; set; }
         public string SmtpAuthen { get; set; }
         public string TlsEncryp { get; set; }
         public string HtmlDirect { get; set; }
         public string IncSubject { get; set; }
         public string TenLevel { get; set; }
         public short CreditDay2 { get; set; }
         public int CdtPrvDays { get; set; }
         public string AuImpRates { get; set; }
         public string ValidateBa { get; set; }
         public string ManRemark { get; set; }
         public string ManRmkType { get; set; }
         public string ManRmkAlt { get; set; }
         public string TermsPath { get; set; }
         public int EDocWSFrm { get; set; }
         public string DspBUoM { get; set; }
         public string EDocSName { get; set; }
         public string EDocSEMail { get; set; }
         public string CpyRulToTx { get; set; }
         public string BpNoLock { get; set; }
         public string SearchUrl { get; set; }
         public string U_CAUTO { get; set; }
         #endregion fields for table OADM
     }
}

