using System;

namespace KTC_SalesAppWAPI.Models.IBTReceipt
{
    public class OWTQ_Ext
    {
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string DocType { get; set; }
        public string CANCELED { get; set; }
        public string Handwrtten { get; set; }
        public string Printed { get; set; }
        public string DocStatus { get; set; }
        public string InvntSttus { get; set; }
        public string Transfered { get; set; }
        public string ObjType { get; set; }
        public DateTime DocDate { get; set; }
        public DateTime DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public string NumAtCard { get; set; }
        public decimal VatPercent { get; set; }
        public decimal VatSum { get; set; }
        public decimal VatSumFC { get; set; }
        public decimal DiscPrcnt { get; set; }
        public decimal DiscSum { get; set; }
        public decimal DiscSumFC { get; set; }
        public string DocCur { get; set; }
        public decimal DocRate { get; set; }
        public decimal DocTotal { get; set; }
        public decimal DocTotalFC { get; set; }
        public decimal PaidToDate { get; set; }
        public decimal PaidFC { get; set; }
        public decimal GrosProfit { get; set; }
        public decimal GrosProfFC { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Comments { get; set; }
        public string JrnlMemo { get; set; }
        public int TransId { get; set; }
        public int ReceiptNum { get; set; }
        public short GroupNum { get; set; }
        public short DocTime { get; set; }
        public int SlpCode { get; set; }
        public short TrnspCode { get; set; }
        public string PartSupply { get; set; }
        public string Confirmed { get; set; }
        public short GrossBase { get; set; }
        public int ImportEnt { get; set; }
        public string CreateTran { get; set; }
        public string SummryType { get; set; }
        public string UpdInvnt { get; set; }
        public string UpdCardBal { get; set; }
        public short Instance { get; set; }
        public int Flags { get; set; }
        public string InvntDirec { get; set; }
        public int CntctCode { get; set; }
        public string ShowSCN { get; set; }
        public string FatherCard { get; set; }
        public decimal SysRate { get; set; }
        public string CurSource { get; set; }
        public decimal VatSumSy { get; set; }
        public decimal DiscSumSy { get; set; }
        public decimal DocTotalSy { get; set; }
        public decimal PaidSys { get; set; }
        public string FatherType { get; set; }
        public decimal GrosProfSy { get; set; }
        public DateTime UpdateDate { get; set; }
        public string IsICT { get; set; }
        public DateTime CreateDate { get; set; }
        public decimal Volume { get; set; }
        public short VolUnit { get; set; }
        public decimal Weight { get; set; }
        public short WeightUnit { get; set; }
        public short Series { get; set; }
        public DateTime TaxDate { get; set; }
        public string Filler { get; set; }
        public string DataSource { get; set; }
        public string StampNum { get; set; }
        public string isCrin { get; set; }
        public int FinncPriod { get; set; }
        public short UserSign { get; set; }
        public string selfInv { get; set; }
        public decimal VatPaid { get; set; }
        public decimal VatPaidFC { get; set; }
        public decimal VatPaidSys { get; set; }
        public short UserSign2 { get; set; }
        public string WddStatus { get; set; }
        public int draftKey { get; set; }
        public decimal TotalExpns { get; set; }
        public decimal TotalExpFC { get; set; }
        public decimal TotalExpSC { get; set; }
        public int DunnLevel { get; set; }
        public string Address2 { get; set; }
        public int LogInstanc { get; set; }
        public string Exported { get; set; }
        public int StationID { get; set; }
        public string Indicator { get; set; }
        public string NetProc { get; set; }
        public decimal AqcsTax { get; set; }
        public decimal AqcsTaxFC { get; set; }
        public decimal AqcsTaxSC { get; set; }
        public decimal CashDiscPr { get; set; }
        public decimal CashDiscnt { get; set; }
        public decimal CashDiscFC { get; set; }
        public decimal CashDiscSC { get; set; }
        public string ShipToCode { get; set; }
        public string LicTradNum { get; set; }
        public string PaymentRef { get; set; }
        public decimal WTSum { get; set; }
        public decimal WTSumFC { get; set; }
        public decimal WTSumSC { get; set; }
        public decimal RoundDif { get; set; }
        public decimal RoundDifFC { get; set; }
        public decimal RoundDifSy { get; set; }
        public string CheckDigit { get; set; }
        public int Form1099 { get; set; }
        public string Box1099 { get; set; }
        public string submitted { get; set; }
        public string PoPrss { get; set; }
        public string Rounding { get; set; }
        public string RevisionPo { get; set; }
        public short Segment { get; set; }
        public DateTime ReqDate { get; set; }
        public DateTime CancelDate { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public string BlockDunn { get; set; }
        public string PeyMethod { get; set; }
        public string PayBlock { get; set; }
        public int PayBlckRef { get; set; }
        public string MaxDscn { get; set; }
        public string Reserve { get; set; }
        public decimal Max1099 { get; set; }
        public string CntrlBnk { get; set; }
        public string PickRmrk { get; set; }
        public string ISRCodLine { get; set; }
        public decimal ExpAppl { get; set; }
        public decimal ExpApplFC { get; set; }
        public decimal ExpApplSC { get; set; }
        public string Project { get; set; }
        public string DeferrTax { get; set; }
        public string LetterNum { get; set; }
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public decimal WTApplied { get; set; }
        public decimal WTAppliedF { get; set; }
        public string BoeReserev { get; set; }
        public string AgentCode { get; set; }
        public decimal WTAppliedS { get; set; }
        public decimal EquVatSum { get; set; }
        public decimal EquVatSumF { get; set; }
        public decimal EquVatSumS { get; set; }
        public short Installmnt { get; set; }
        public string VATFirst { get; set; }
        public decimal NnSbAmnt { get; set; }
        public decimal NnSbAmntSC { get; set; }
        public decimal NbSbAmntFC { get; set; }
        public decimal ExepAmnt { get; set; }
        public decimal ExepAmntSC { get; set; }
        public decimal ExepAmntFC { get; set; }
        public DateTime VatDate { get; set; }
        public string CorrExt { get; set; }
        public int CorrInv { get; set; }
        public int NCorrInv { get; set; }
        public string CEECFlag { get; set; }
        public decimal BaseAmnt { get; set; }
        public decimal BaseAmntSC { get; set; }
        public decimal BaseAmntFC { get; set; }
        public string CtlAccount { get; set; }
        public int BPLId { get; set; }
        public string BPLName { get; set; }
        public string VATRegNum { get; set; }
        public string TxInvRptNo { get; set; }
        public DateTime TxInvRptDt { get; set; }
        public string KVVATCode { get; set; }
        public string WTDetails { get; set; }
        public int SumAbsId { get; set; }
        public DateTime SumRptDate { get; set; }
        public string PIndicator { get; set; }
        public string ManualNum { get; set; }
        public string UseShpdGd { get; set; }
        public decimal BaseVtAt { get; set; }
        public decimal BaseVtAtSC { get; set; }
        public decimal BaseVtAtFC { get; set; }
        public decimal NnSbVAt { get; set; }
        public decimal NnSbVAtSC { get; set; }
        public decimal NbSbVAtFC { get; set; }
        public decimal ExptVAt { get; set; }
        public decimal ExptVAtSC { get; set; }
        public decimal ExptVAtFC { get; set; }
        public decimal LYPmtAt { get; set; }
    }
}
