using System;

namespace KTC_SalesAppWAPI.Models.IBTReceipt
{
    public class WTQ1_Ext
    {
        public int DocEntry { get; set; }
        public int LineNum { get; set; }
        public int TargetType { get; set; }
        public int TrgetEntry { get; set; }
        public string BaseRef { get; set; }
        public int BaseType { get; set; }
        public int BaseEntry { get; set; }
        public int BaseLine { get; set; }
        public string LineStatus { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public decimal Quantity { get; set; }
        public DateTime ShipDate { get; set; }
        public decimal OpenQty { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public decimal Rate { get; set; }
        public decimal DiscPrcnt { get; set; }
        public decimal LineTotal { get; set; }
        public decimal TotalFrgn { get; set; }
        public decimal OpenSum { get; set; }
        public decimal OpenSumFC { get; set; }
        public string VendorNum { get; set; }
        public string SerialNum { get; set; }
        public string WhsCode { get; set; }
        public int SlpCode { get; set; }
        public decimal Commission { get; set; }
        public string TreeType { get; set; }
        public string AcctCode { get; set; }
        public string TaxStatus { get; set; }
        public decimal GrossBuyPr { get; set; }
        public decimal PriceBefDi { get; set; }
        public DateTime DocDate { get; set; }
        public int Flags { get; set; }
        public decimal OpenCreQty { get; set; }
        public string UseBaseUn { get; set; }
        public string SubCatNum { get; set; }
        public string BaseCard { get; set; }
        public decimal TotalSumSy { get; set; }
        public decimal OpenSumSys { get; set; }
        public string InvntSttus { get; set; }
        public string OcrCode { get; set; }
        public string Project { get; set; }
        public string CodeBars { get; set; }
        public decimal VatPrcnt { get; set; }
        public string VatGroup { get; set; }
        public decimal PriceAfVAT { get; set; }
        public decimal Height1 { get; set; }
        public short Hght1Unit { get; set; }
        public decimal Height2 { get; set; }
        public short Hght2Unit { get; set; }
        public decimal Width1 { get; set; }
        public short Wdth1Unit { get; set; }
        public decimal Width2 { get; set; }
        public short Wdth2Unit { get; set; }
        public decimal Length1 { get; set; }
        public short Len1Unit { get; set; }
        public decimal length2 { get; set; }
        public short Len2Unit { get; set; }
        public decimal Volume { get; set; }
        public short VolUnit { get; set; }
        public decimal Weight1 { get; set; }
        public short Wght1Unit { get; set; }
        public decimal Weight2 { get; set; }
        public short Wght2Unit { get; set; }
        public decimal Factor1 { get; set; }
        public decimal Factor2 { get; set; }
        public decimal Factor3 { get; set; }
        public decimal Factor4 { get; set; }
        public decimal PackQty { get; set; }
        public string UpdInvntry { get; set; }
        public int BaseDocNum { get; set; }
        public string BaseAtCard { get; set; }
        public string SWW { get; set; }
        public decimal VatSum { get; set; }
        public decimal VatSumFrgn { get; set; }
        public decimal VatSumSy { get; set; }
        public int FinncPriod { get; set; }
        public string ObjType { get; set; }
        public int LogInstanc { get; set; }
        public string BlockNum { get; set; }
        public string ImportLog { get; set; }
        public decimal DedVatSum { get; set; }
        public decimal DedVatSumF { get; set; }
        public decimal DedVatSumS { get; set; }
        public string IsAqcuistn { get; set; }
        public decimal DistribSum { get; set; }
        public decimal DstrbSumFC { get; set; }
        public decimal DstrbSumSC { get; set; }
        public decimal GrssProfit { get; set; }
        public decimal GrssProfSC { get; set; }
        public decimal GrssProfFC { get; set; }
        public int VisOrder { get; set; }
        public decimal INMPrice { get; set; }
        public int PoTrgNum { get; set; }
        public string PoTrgEntry { get; set; }
        public string DropShip { get; set; }
        public int PoLineNum { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string OrigItem { get; set; }
        public string BackOrdr { get; set; }
        public string FreeTxt { get; set; }
        public string PickStatus { get; set; }
        public decimal PickOty { get; set; }
        public int PickIdNo { get; set; }
        public short TrnsCode { get; set; }
        public decimal VatAppld { get; set; }
        public decimal VatAppldFC { get; set; }
        public decimal VatAppldSC { get; set; }
        public decimal BaseQty { get; set; }
        public decimal BaseOpnQty { get; set; }
        public decimal VatDscntPr { get; set; }
        public string WtLiable { get; set; }
        public string DeferrTax { get; set; }
        public decimal EquVatPer { get; set; }
        public decimal EquVatSum { get; set; }
        public decimal EquVatSumF { get; set; }
        public decimal EquVatSumS { get; set; }
        public decimal LineVat { get; set; }
        public decimal LineVatlF { get; set; }
        public decimal LineVatS { get; set; }
        public string unitMsr { get; set; }
        public decimal NumPerMsr { get; set; }
        public string CEECFlag { get; set; }
        public decimal ToStock { get; set; }
        public decimal ToDiff { get; set; }
        public decimal ExciseAmt { get; set; }
        public decimal TaxPerUnit { get; set; }
        public decimal TotInclTax { get; set; }
        public string CountryOrg { get; set; }
        public decimal StckDstSum { get; set; }
        public decimal ReleasQtty { get; set; }
        public string LineType { get; set; }
        public string TranType { get; set; }
        public string Text { get; set; }
        public int OwnerCode { get; set; }
        public decimal StockPrice { get; set; }
        public string ConsumeFCT { get; set; }
        public decimal LstByDsSum { get; set; }
        public decimal StckINMPr { get; set; }
        public decimal LstBINMPr { get; set; }
        public decimal StckDstFc { get; set; }
        public decimal StckDstSc { get; set; }
        public decimal LstByDsFc { get; set; }
        public decimal LstByDsSc { get; set; }
        public decimal StockSum { get; set; }
        public decimal StockSumFc { get; set; }
        public decimal StockSumSc { get; set; }
        public decimal StckSumApp { get; set; }
        public decimal StckAppFc { get; set; }
        public decimal StckAppSc { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToDesc { get; set; }
        public decimal StckAppD { get; set; }
        public decimal StckAppDFC { get; set; }
        public decimal StckAppDSC { get; set; }
        public string BasePrice { get; set; }
        public decimal GTotal { get; set; }
        public decimal GTotalFC { get; set; }
        public decimal GTotalSC { get; set; }
        public string DistribExp { get; set; }
        public string DescOW { get; set; }
        public string DetailsOW { get; set; }
        public short GrossBase { get; set; }
        public decimal VatWoDpm { get; set; }
        public decimal VatWoDpmFc { get; set; }
        public decimal VatWoDpmSc { get; set; }
        public string CFOPCode { get; set; }
        public string CSTCode { get; set; }
        public int Usage { get; set; }
        public string TaxOnly { get; set; }
        public string WtCalced { get; set; }
        public decimal QtyToShip { get; set; }
        public decimal DelivrdQty { get; set; }
        public decimal OrderedQty { get; set; }
        public string CogsOcrCod { get; set; }
        public int CiOppLineN { get; set; }
        public string CogsAcct { get; set; }
        public string ChgAsmBoMW { get; set; }
        public DateTime ActDelDate { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public decimal TaxDistSum { get; set; }
    }
}
